### PR TITLE
added support for gzip/deflate compressionLevel

### PR DESCRIPTION
**Pull request by illes**

### CODE REVIEW

**Comment by illes** [comment]
@fgaule, are there any other requirements to merge this feature?

**Comment by fgaule** [comment]
@illes yes, just reformat the code and i will merge it.

**Comment by illes** [comment]
@fgaule, okay, i'll reformat the lines changed. Note, however, that the indentations used in this pull request are following that of the original code context -- those may need to be formatted as well, just like https://github.com/ziplet/ziplet/pull/21 suggests

**Comment by fgaule** [comment]
@illes yes, sure, it's a pitty the guy who did the PR never fixed his branch.

**Comment by fgaule** [comment]
@illes version 2.3.0 has been released including this. Thanks!

**Pull request merged**
